### PR TITLE
Update order details

### PR DESCRIPTION
**Pull request by Tenzin-Jorden**
Changed the Order_Id, Sponsor_Id and Study_Id to their original position.

### CODE REVIEW

**Review by Mastaleru — CHANGES_REQUESTED** [review]
for what task is this change?
I did created a task for changing the order of the input fields on the creation/reviewing the order

**Comment by Tenzin-Jorden** [comment]
> for what task is this change?
> I did created a task for changing the order of the input fields on the creation/reviewing the order

Issue - The header and records were misaligned. eg - OrderID(header) contains Study_id(record) in the table.
I solved this issue.

**Comment by Mastaleru** [comment]
Issue #89 refers to sponsor SPO SSApp. Let me remind that the actors abbreviations: 
SPO - Sponsor
CMO - Contract Manufacturing Organization
COU - Courier
CSI/SITE - Clinical Site

1. You made changes in the wrong SSApp.
2. Your changes were impacted on the View Order page and on the Review page. It can be easily see that there are some inputs, but in the table were I requested changes there are no inputs. 
3. Why are you using 2 different GitHub accounts?

**Review by Mastaleru — COMMENTED** [review]
no changes are needed in this file

**Pull request closed without merging**
