### PR TITLE
Integrate #793 with master.

### PR DESCRIPTION
**Pull request by arispapapro**

### CODE REVIEW

**Review by Mastaleru — CHANGES_REQUESTED** [review]
what about the rest of the buttons?

**Comment by arispapapro** [comment]
Implement it with webcardinal expressions

**Comment by Mastaleru** [comment]
> what about the rest of the buttons?

again, @aris, where are the rest of buttons?

**Comment by arispapapro** [comment]
I need to make the buttons disabled both when its invalid or while we are submitting and the loader is up. If the loader is missing i have to add this there.

**Comment by arispapapro** [comment]
image


This Error comes up and prevents me from developing there.

**Comment by Mastaleru** [comment]
too many strange merges and conflicts even if you are the single one who is working in this area.

**Pull request closed without merging**
