### PR TITLE
#536 - Improved search results by including all column

### PR DESCRIPTION
**Pull request by abhayprasadnovartis**
Improved search results by including all column for all actors

### CODE REVIEW

**Review by Mastaleru — CHANGES_REQUESTED** [review]
please explain the reason of introducing the new method getSearchedProps?

**Comment by abhayprasadnovartis** [comment]
> please explain the reason of introducing the new method getSearchedProps?

This function returns the respective table header columns based on the role. (CMO, SITE, SPO, COU)

**Comment by Mastaleru** [comment]
and what is this function doing? 
image

**Comment by abhayprasadnovartis** [comment]
> and what is this function doing? image

Ok, I will use the existing method and commit changes.

**Comment by abhayprasadnovartis** [comment]
Changes committed.

**Review by Mastaleru — CHANGES_REQUESTED** [review]
I don't see the need of adding extra properties for table headers, while you already have the property notSortable for the View column. 

And there is no reason to have the getSearchedProperties function 

You can simply write like this:

this.searchedProps = tableHeaders.filter(header=>header.notSortable===false).map( header => header.column)

**Comment by abhayprasadnovartis** [comment]
> I don't see the need of adding extra properties for table headers, while you already have the property notSortable for the View column.
> 
> And there is no reason to have the getSearchedProperties function
> 
> You can simply write like this:
> 
> this.searchedProps = tableHeaders.filter(header=>header.notSortable===false).map( header => header.column)

I have written extra property "value" because the column heading and field name is different for example (deliveryDate_value, requestDate_value, status_value).

**Review by Mastaleru — CHANGES_REQUESTED** [review]
why do you need the changes on constants?

**Comment by abhayprasadnovartis** [comment]
Removed value field from constant

**Review by Mastaleru — CHANGES_REQUESTED** [review]
why Search service should know about shipperID?
status_value can be skipeed 
what is the purpose of forDeletion?

**Comment by abhayprasadnovartis** [comment]
forDeletion contains fields which we don't need in searchedProperties.
shipperID based search should be based on field shipperId and not (shipperID)
I will remove status_value if search based on status not required.

**Comment by Mastaleru** [comment]
I remember that we discussed about usage of notSortable field in order to avoid inclusion of columns that we don't want.
why don't you change the shipperID to shipperId in constants?


available, assigned, dispensed could also be notSortable

**Review by Mastaleru — CHANGES_REQUESTED** [review]
this.searchedProps = kitsTableHeaders.filter(header=>header.notSortable===false).map( header => header.column); should be move into SearchSerice constructor

**Review by Mastaleru — APPROVED** [review]

**Pull request merged**
