### PR TITLE
#317 Changes finished

### PR DESCRIPTION
**Pull request by abhayprasadnovartis**
Implemented COU Scan and deliver shipment screens without modal. Below is snapshot
image

### CODE REVIEW

**Review by Mastaleru — CHANGES_REQUESTED** [review]
why did you added CourierSIngleShipmentControllerImpl in services?
We already have implemented CourierSingleShipmentController in courier

**Comment by Mastaleru** [comment]
Also add the Deliver Shipment label in the breadcrumb (in deliver-shipment.html)

Here:
       <span data-tag='dashboard'>Dashboard</span> / <span data-tag='dashboard'>Shipments</span> /  <strong>{{@shipment.shipmentId}}</strong> / <strong>Deliver Shipment</strong>

**Comment by abhayprasadnovartis** [comment]
> why did you added CourierSIngleShipmentControllerImpl in services? We already have implemented CourierSingleShipmentController in courier

Removed CourierSingleShipmentControllerImpl from service

**Comment by abhayprasadnovartis** [comment]
> Also add the Deliver Shipment label in the breadcrumb (in deliver-shipment.html)
> 
> Here: Dashboard / Shipments / **{{@shipment.shipmentId}}** / **Deliver Shipment**

Appended this text in design

**Review by Mastaleru — APPROVED** [review]

**Pull request merged**
