### PR TITLE
bug fix #49

### LINKED ISSUE #49: Implement deletion on current attached documents
Now deletion is not implemented but the UI is showing icons for deleting attached documents for both the Sponsor and CMO. Deletion should work only for the current attached documents that haven't already been saved in the documentsDSU.

Provided mockup:

CMO_Review-Order-15

### PR DESCRIPTION
**Pull request by arijitnv**
I have fixed the bug for issue #49. Kindly review the latest changes.

### CODE REVIEW

**Review by Mastaleru — CHANGES_REQUESTED** [review]
why do you iterate over the documents when the `event`  is actually the document that you want to remove

**Comment by arijitnv** [comment]
> why do you iterate over the documents when the `event` is actually the document that you want to remove

I have modified the logic. Please have a look and let me know your comments.

**Review by Mastaleru — CHANGES_REQUESTED** [review]
I think it is a difference between a random number and an uuid. let's not confuse people who reads this

**Review by Mastaleru — APPROVED** [review]

**Review by Mastaleru — APPROVED** [review]
in js strict equality  (===) usage is encouraged where applicable

**Pull request merged**
